subprojects=(
    jqa-uber-parent
    jqa-own-constraints
    jqa-checkstyle-config
    jqa-asciidoctor-utilities
    jqa-neo4j-backend
    jqa-core-framework
    jqa-plugin-parent
    jqa-plugin-common
    jqa-asciidoc-report-plugin
    jqa-xml-plugin
    jqa-java-plugin
    jqa-yaml-plugin
    jqa-yaml2-plugin
    jqa-junit-plugin
    jqa-java8-plugin
    jqa-jpa2-plugin
    jqa-jaxrs-plugin
    jqa-cdi-plugin
    jqa-ejb3-plugin
    jqa-javaee6-plugin
    jqa-testng-plugin
    jqa-osgi-plugin
    jqa-maven3-plugin
    jqa-tycho-plugin
    jqa-rdbms-plugin
    jqa-m2repo-plugin
    jqa-json-plugin
    jqa-graphml-plugin
    jqa-graphql-plugin
    jqa-spring-plugin
    jqa-distribution-specification
    jqa-maven-plugin
    jqa-commandline-tool
    jqa-manual
);

#jqa-archivers-plugin # Noch nicht Teil der Distribution. 21.01.2017
